# -*- coding: utf-8 -*-
"""lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UcORkuSiOFksnaViFF81qSamna63JGI
"""

c=['a','b','c','d','e','f']
print(c[1:3])

print(c[1:-2])

def calculate_marks(age, hours_studied):
  base_marks = 50
  if age >= 18 and age <=25:
      base_marks += (age-18)*2
  if hours_studied >=5:
      base_marks += (hours_studied-5)*5
  return base_marks
age = int(input("Enter your age: "))
hours_studied = int(input("Enter the number of hours you studied: "))
marks = calculate_marks(age, hours_studied)
print("Your estimated marks are:", marks)

a=42
print(a)

A=20
B=10
print(A+B)

my_list=[1,a,1.25,'hyderabad']
print(my_list)
my_list.append('alpha')
print(my_list)
my_list.pop()
my_list.remove(1)
print(my_list)

for i in range(1,10):
    print(i)

i=1
while i<=10:
    print(i)
    i+=1

n = int(input("Enter a number: "))
if n > 0:
    print("The number is positive")
elif n<0:
    print("The number is negative")
else:
    print("The number is zero.")

def greet(name):
    print("Hello, " + name + "!")
greet("yuvaraj")



