# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UcORkuSiOFksnaViFF81qSamna63JGI
"""

c=['a','b','c','d','e','f']
print(c[1:3])

print(c[1:-2])

def calculate_marks(age, hours_studied):
  base_marks = 50
  if age >= 18 and age <=25:
      base_marks += (age-18)*2
  if hours_studied >=5:
      base_marks += (hours_studied-5)*5
  return base_marks
age = int(input("Enter your age: "))
hours_studied = int(input("Enter the number of hours you studied: "))
marks = calculate_marks(age, hours_studied)
print("Your estimated marks are:", marks)